### ISSUE TITLE
Socket error in Google Discovery API

### ISSUE THREAD

**Issue by JoshuaFox** [doitintl/iris3#5]
- An occasional  socket failure in getting info on a project
- see known issue in [Google Client here](https://github.com/googleapis/google-api-python-client/issues/1397)
 - Recommended: switch to this library for Discovery https://github.com/googleapis/google-cloud-python

**Comment by JoshuaFox** [comment]
This happens irregularly
```

Traceback (most recent call last):
  File "/srv/main.py", line 88, in label_one
    __label_one_0(data, plugin)
  File "/srv/main.py", line 102, in __label_one_0
    plugin.label_one(gcp_object, project_id)
  File "/srv/plugins/instances.py", line 88, in label_one
    labels = self._build_labels(gcp_object, project_id)
  File "/srv/plugin.py", line 147, in _build_labels
    self._project_labels(project_id) if is_copying_labels_from_project() else {}
  File "/srv/plugin.py", line 48, in _project_labels
    response = request.execute()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/googleapiclient/http.py", line 900, in execute
    resp, content = _retry_request(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/googleapiclient/http.py", line 204, in _retry_request
    raise exception
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/httplib2/__init__.py", line 1708, in request
    (response, content) = self._request(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/httplib2/__init__.py", line 1424, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/httplib2/__init__.py", line 1347, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/opt/python3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/python3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/python3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/python3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/opt/python3.9/lib/python3.9/http/client.py", line 969, in send
    self.sock.sendall(data)
  File "/opt/python3.9/lib/python3.9/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/opt/python3.9/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe 
```

**Comment by JoshuaFox** [comment]
Switched to [ new API ](https://github.com/googleapis/google-cloud-python)for the problematic line only.

DId not replace all uses of old _googleapiclient_ API because _googleapiclient_  is still supported and the new API is partly in beta.
